"""Original related-word pairs. Kept on the server, never shipped to players."""
# Each word includes a short explanation; the pair shares a familiar category.
PAIRS = [
    (('Coffee', 'A drink brewed from roasted beans.'), ('Tea', 'A drink made by steeping leaves in hot water.')),
    (('River', 'A natural stream of water flowing across land.'), ('Canal', 'A waterway built by people for transport or irrigation.')),
    (('Ocean', 'A vast body of salt water.'), ('Lake', 'A body of water surrounded by land.')),
    (('Mountain', 'A very high natural rise in the land.'), ('Hill', 'A raised area of land smaller than a mountain.')),
    (('Bicycle', 'A two-wheeled vehicle powered by pedals.'), ('Motorcycle', 'A two-wheeled vehicle powered by an engine.')),
    (('Train', 'Connected vehicles that travel on railway tracks.'), ('Tram', 'A passenger vehicle running on tracks through city streets.')),
    (('Bus', 'A large road vehicle carrying many passengers.'), ('Taxi', 'A car hired for a particular journey.')),
    (('Helicopter', 'An aircraft lifted by rotating blades.'), ('Airplane', 'An aircraft with fixed wings.')),
    (('Piano', 'A keyboard instrument whose hammers strike strings.'), ('Organ', 'A keyboard instrument with sustained tones, traditionally made by pipes.')),
    (('Guitar', 'A string instrument usually played by strumming or plucking.'), ('Violin', 'A small string instrument usually played with a bow.')),
    (('Drum', 'An instrument sounded by striking a stretched surface.'), ('Tambourine', 'A small hand-held percussion instrument with metal jingles.')),
    (('Library', 'A place where books can be read or borrowed.'), ('Bookshop', 'A shop where books are sold.')),
    (('Museum', 'A place displaying objects of historical, artistic, or scientific interest.'), ('Gallery', 'A place displaying works of art.')),
    (('Hotel', 'A building offering rooms for travellers.'), ('Hostel', 'Budget accommodation often with shared sleeping rooms.')),
    (('School', 'A place where children receive lessons.'), ('University', 'An institution offering advanced study and degrees.')),
    (('Bakery', 'A place that makes and sells bread and baked goods.'), ('Cafe', 'A place serving drinks and light meals.')),
    (('Beach', 'A sandy or pebbly shore beside water.'), ('Desert', 'A very dry region with little rainfall.')),
    (('Rain', 'Water falling from clouds in drops.'), ('Snow', 'Frozen water falling from clouds in flakes.')),
    (('Fog', 'A thick cloud of tiny water droplets near the ground.'), ('Cloud', 'A visible mass of water droplets or ice in the sky.')),
    (('Lightning', 'A sudden flash of electricity during a storm.'), ('Thunder', 'The loud sound caused by lightning.')),
    (('Candle', 'Wax with a wick that burns to give light.'), ('Lantern', 'A portable light with a protective covering.')),
    (('Torch', 'A hand-held portable electric light.'), ('Lamp', 'A device that lights a room or work area.')),
    (('Sofa', 'A padded seat for several people.'), ('Armchair', 'A comfortable padded seat for one person.')),
    (('Blanket', 'A warm covering used on a bed or around the body.'), ('Quilt', 'A bed covering made of stitched layers with filling.')),
    (('Pillow', 'A soft support for the head when lying down.'), ('Cushion', 'A soft pad used for comfort on a seat.')),
    (('Spoon', 'A utensil with a small bowl for scooping food.'), ('Fork', 'A utensil with prongs for picking up food.')),
    (('Plate', 'A flat dish used to serve food.'), ('Bowl', 'A deep rounded dish used to hold food.')),
    (('Bottle', 'A container with a narrow neck for liquids.'), ('Jar', 'A wide-mouthed container with a lid.')),
    (('Mango', 'A sweet tropical fruit with a large flat stone.'), ('Peach', 'A soft sweet fruit with fuzzy skin and a hard stone.')),
    (('Lemon', 'A sour yellow citrus fruit.'), ('Lime', 'A small sour citrus fruit usually with green skin.')),
    (('Apple', 'A round firm fruit with a central core.'), ('Pear', 'A sweet fruit usually narrow at the stem and wider below.')),
    (('Potato', 'A starchy underground vegetable often boiled or fried.'), ('Sweet potato', 'A sweet-tasting root vegetable often orange inside.')),
    (('Onion', 'A layered vegetable with a sharp smell and taste.'), ('Garlic', 'A strongly flavoured bulb divided into cloves.')),
    (('Pizza', 'A baked flat base topped with sauce, cheese, and other ingredients.'), ('Sandwich', 'Food placed between pieces of bread.')),
    (('Cake', 'A sweet baked food often served at celebrations.'), ('Muffin', 'A small individual baked cake, often eaten at breakfast.')),
    (('Ice cream', 'A sweet frozen dessert made with milk or cream.'), ('Sorbet', 'A frozen dessert made with fruit and water.')),
    (('Honey', 'A sweet sticky food made by bees.'), ('Jam', 'A sweet spread made by cooking fruit with sugar.')),
    (('Lion', 'A large wild cat; males usually have a mane.'), ('Tiger', 'A large wild cat with dark stripes.')),
    (('Wolf', 'A wild canine that often lives and hunts in packs.'), ('Fox', 'A smaller wild canine with a bushy tail.')),
    (('Dolphin', 'An intelligent marine mammal with a curved dorsal fin.'), ('Shark', 'A fish with a skeleton made of cartilage and several rows of teeth.')),
    (('Butterfly', 'An insect with broad often colourful wings.'), ('Moth', 'A winged insect often active at night.')),
    (('Bee', 'A flying insect known for collecting pollen and making honey.'), ('Wasp', 'A narrow-waisted flying insect that can sting.')),
    (('Crocodile', 'A large water-dwelling reptile with a long pointed snout.'), ('Alligator', 'A large water-dwelling reptile with a broad rounded snout.')),
    (('Owl', 'A bird of prey with large eyes, often active at night.'), ('Eagle', 'A large bird of prey with powerful wings and sharp vision.')),
    (('Football', 'A team game in which players kick a ball toward a goal.'), ('Basketball', 'A team game in which players throw a ball through a raised hoop.')),
    (('Tennis', 'A racket sport played across a net with a bouncing ball.'), ('Badminton', 'A racket sport played across a net with a shuttlecock.')),
    (('Chess', 'A strategy board game with kings, queens, and other pieces.'), ('Checkers', 'A board game with counters that jump over opponents.')),
    (('Swimming', 'Moving through water using the arms and legs.'), ('Diving', 'Entering water headfirst or exploring below its surface.')),
    (('Painting', 'Making an image using coloured liquid applied to a surface.'), ('Drawing', 'Making an image using lines from a pencil, pen, or similar tool.')),
    (('Camera', 'A device used to take photographs or record video.'), ('Binoculars', 'A pair of linked lenses used to see distant objects.')),
    (('Clock', 'A device that shows the time.'), ('Stopwatch', 'A device that measures how long an event takes.')),
    (('Map', 'A drawing showing the layout of places.'), ('Compass', 'An instrument with a needle that points north.')),
    (('Passport', 'An official document used for international travel.'), ('Ticket', 'A document giving permission to travel or enter an event.')),
    (('Suitcase', 'A case used to carry clothes while travelling.'), ('Backpack', 'A bag carried on the back using shoulder straps.')),
    (('Boots', 'Footwear covering the foot and part of the leg.'), ('Sneakers', 'Comfortable shoes often used for sports or walking.')),
    (('Scarf', 'A piece of cloth worn around the neck or head.'), ('Shawl', 'A large piece of cloth worn over the shoulders.')),
    (('Necklace', 'Jewellery worn around the neck.'), ('Bracelet', 'Jewellery worn around the wrist.')),
    (('Doctor', 'A professional who diagnoses and treats illness.'), ('Nurse', 'A professional who provides and coordinates patient care.')),
    (('Chef', 'A professional who prepares and cooks food.'), ('Baker', 'A person who makes bread, cakes, and other baked food.')),
    (('Garden', 'An area where plants and flowers are grown.'), ('Park', 'A public open space for recreation.')),
]
